# Generated by Django 4.0.6 on 2022-08-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image1', models.ImageField(upload_to='')),
            ],
        ),
    ]
